### ISSUE TITLE
build fails on missing generate_extra_images.mk

### ISSUE THREAD

**Issue by wdehoog** [ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one#7]
I followed your build instructions on the oneplus forum but unfortunately it does not work on my machine (ubuntu 14.04 amd64). The last output is:
 
build/core/Makefile:32: warning: overriding commands for target `/home/neil/phablet.manual/out/target/product/bacon/system/etc/apns-conf.xml'
build/core/base_rules.mk:529: warning: ignoring old commands for target `/home/neil/phablet.manual/out/target/product/bacon/system/etc/apns-conf.xml'
PRODUCT_COPY_FILES device/sample/etc/apns-full-conf.xml:system/etc/apns-conf.xml ignored.
PRODUCT_COPY_FILES device/oppo/msm8974-common/audio/mixer_paths.xml:system/etc/mixer_paths.xml ignored.
No private recovery resources for TARGET_DEVICE bacon
device/oneplus/bacon/mkbootimg.mk:47: warning: overriding commands for target `/home/neil/phablet.manual/out/target/product/bacon/boot.img'
build/core/Makefile:489: warning: ignoring old commands for target `/home/neil/phablet.manual/out/target/product/bacon/boot.img'
make: *** No rule to make target `build/core/generate_extra_images.mk'.  Stop.

**Comment by robbyf** [comment]
This file needs to be included in build_core

https://github.com/CyanogenMod/android_build/blob/cm-11.0/core/generate_extra_images.mk

**Comment by wdehoog** [comment]
Thanks. It seems to help. Ran into problem whch seem to be solved with your fix for issue 6. Now it stops with:

target thumb C++: keystore.msm8974 <= hardware/qcom/keymaster/keymaster_qcom.cpp
hardware/qcom/keymaster/keymaster_qcom.cpp:32:27: fatal error: linux/msm_ion.h: No such file or directory
compilation terminated.
make: *** [/home/neil/phablet.manual/out/target/product/bacon/obj/SHARED_LIBRARIES/keystore.msm8974_intermediates/keymaster_qcom.o] Error 1

**Comment by mariogrip** [comment]
did you update your manifests? 
https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/blob/master/manifest.xml

 ```Line 103: <project path="hardware/qcom/keymaster" name="qcom-keymaster" remote="opo" revision="phablet-4.4.2_r1" groups="qcom" /> ```

**Comment by mariogrip** [comment]
The main issue is fixed, commit: https://github.com/ubuntu-touch-oneplus-one/android_device_oneplus_bacon/commit/6ceb79f7e9d3c7d1bafa2e578f458130afe36231
